# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            David Chang
tagline:          'The _other_ David Chang'
description:      'Development notes and side projects. Tweet me at <a href="https://twitter.com/davidchchang" target="_blank">@davidchchang</a>.'
url:              http://davidchchang.com

author:
  name:           'David Chang'
  url:            https://twitter.com/davidchchang

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/davidchchang
