# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            David Chang
tagline:          'The _other_ David Chang'
description:      'Development notes and side projects. <a href="https://github.com/poole/hyde" target="_blank">Hyde</a> theme created by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://davidchchang.com
baseurl:          /

author:
  name:           'David Chang'
  url:            https://twitter.com/davidchchang

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/davidchchang/davidchchang.github.io
